// src/pages/AddVehicle.jsx
import React, { useEffect, useRef, useState } from "react";
import { useNavigate, useLocation, Link } from "react-router-dom";
import * as Icons from "lucide-react";
import { motion } from "framer-motion";
import {
  addDoc,
  collection,
  doc as firestoreDoc,
  getDoc,
  updateDoc,
  deleteDoc,
  serverTimestamp,
} from "firebase/firestore";
import { ref as storageRef, uploadBytesResumable, getDownloadURL } from "firebase/storage";
import { db, storage } from "../../firebase";

/* ---------------- helpers ---------------- */
function useQuery() {
  const { search } = useLocation();
  return React.useMemo(() => new URLSearchParams(search), [search]);
}
function makePublicId(model = "") {
  const base = model ? model.trim().replace(/\s+/g, "_").replace(/[^\w\-]/g, "") : "veh";
  const suffix = String(Date.now()).slice(-5);
  return `${base}_${suffix}`;
}
function makeCustomerIdFromName(name = "") {
  const base = name
    .toLowerCase()
    .trim()
    .split(" ")
    .slice(0, 2)
    .map((p) => p.replace(/[^\w]/g, ""))
    .join("_")
    .slice(0, 12) || "cust";
  const suffix = String(Date.now()).slice(-6);
  return `${base}_${suffix}`;
}
function generateFriendlyId(model = "") {
  const base = model ? model.trim().replace(/\s+/g, "_").replace(/[^\w\-]/g, "") : "veh";
  const t = String(Date.now()).slice(-6);
  return `${base}_${t}`;
}

/* ---------------- Pricing mapping ---------------- */
const TYPE_PRICING = {
  "Comfort / Hala Taxi": { baseFare: 8.0, pricePerKm: 2.0 },
  Executive: { baseFare: 18.0, pricePerKm: 3.5 },
  Electric: { baseFare: 8.0, pricePerKm: 1.8 },
  Premier: { baseFare: 16.0, pricePerKm: 3.2 },
  "Eco-friendly": { baseFare: 8.0, pricePerKm: 1.9 },
  "Hala Max": { baseFare: 18.0, pricePerKm: 4.0 },
  "Max 6": { baseFare: 18.0, pricePerKm: 3.8 },
  Default: { baseFare: 10.0, pricePerKm: 2.5 },
};

const CATEGORY_OPTIONS = [
  "Comfort / Hala Taxi",
  "Executive",
  "Electric",
  "Premier",
  "Eco-friendly",
  "Hala Max",
  "Max 6",
];

/* Map common carType keywords to suggested category */
const CAR_TYPE_TO_CATEGORY = [
  { match: /hatch|alto|i10|swift|micra|c1/i, category: "Comfort / Hala Taxi" },
  { match: /sedan|amaze|corolla|city|verna|entra/i, category: "Comfort / Hala Taxi" },
  { match: /suv|xuv|creta|fortuner|pajero|harrier|tiger/i, category: "Executive" },
  { match: /mpv|muv|ertiga|innova|shiv/i, category: "Hala Max" },
  { match: /van|traveller|minivan|hiace|sprinter/i, category: "Max 6" },
  { match: /electric|ev|tesla|leaf|bolt/i, category: "Electric" },
  { match: /premium|lux|mercedes|bmw|audi|lexus/i, category: "Premier" },
];

export default function AddVehicle() {
  const navigate = useNavigate();
  const q = useQuery();
  const initialCustomerId = q.get("customerId") || "";
  const vehicleIdParam = q.get("vehicleId") || null; // expects ?vehicleId=<docId>

  const fileInputRef = useRef(null);

  const [isEdit] = useState(Boolean(vehicleIdParam));
  const [vehicleDocId, setVehicleDocId] = useState(vehicleIdParam || null);

  const [customerNameInput, setCustomerNameInput] = useState("");
  const [customerNameFetched, setCustomerNameFetched] = useState("");
  const [loadingCustomer, setLoadingCustomer] = useState(false);

  const [customerId, setCustomerId] = useState(initialCustomerId);
  const [autoGeneratedCustomerId, setAutoGeneratedCustomerId] = useState(false);

  const [form, setForm] = useState({
    brand: "",
    brandImageUrl: "",
    model: "",
    publicId: "",
    carType: "",
    category: "",
    licensePlateNumber: "",
    registration: "",
    color: "",
    seats: "",
    transmission: "",
    fuelType: "",
    city: "",
    yearOfManufacture: "",
    baseFare: "",
    pricePerKm: "",
  });

  const [existingImageUrl, setExistingImageUrl] = useState(null);
  const [file, setFile] = useState(null);
  const [preview, setPreview] = useState(null);
  const [uploadProgress, setUploadProgress] = useState(0);

  const [loadingDoc, setLoadingDoc] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState(null);

  // track if user touched price inputs to avoid overwriting their edits when category changes
  const [priceTouched, setPriceTouched] = useState(false);
  // track if category was auto-selected
  const [categoryAutoSelected, setCategoryAutoSelected] = useState(false);

  /* ---------- load doc if edit ---------- */
  useEffect(() => {
    if (!vehicleDocId) return;
    let mounted = true;
    setLoadingDoc(true);
    getDoc(firestoreDoc(db, "customer_cars", vehicleDocId))
      .then((snap) => {
        if (!mounted) return;
        if (snap.exists()) {
          const d = snap.data();
          setForm({
            brand: d.brand || "",
            brandImageUrl: d.brandImage || "",
            model: d.model || "",
            publicId: d.publicId || (d.model ? makePublicId(d.model) : ""),
            carType: d.carType || "",
            category: d.category || "",
            licensePlateNumber: d.licensePlateNumber || "",
            registration: d.registration || "",
            color: d.color || "",
            seats: d.seats || "",
            transmission: d.transmission || "",
            fuelType: d.fuelType || "",
            city: d.city || "",
            yearOfManufacture: d.yearOfManufacture || "",
            baseFare: d.baseFare != null ? String(d.baseFare) : "",
            pricePerKm: d.pricePerKm != null ? String(d.pricePerKm) : "",
          });
          setExistingImageUrl(d.image || d.brandImage || null);
          if (!customerId && d.customerId) {
            setCustomerId(d.customerId);
            setAutoGeneratedCustomerId(false);
          }
          if (d.customerId) {
            getDoc(firestoreDoc(db, "customer", d.customerId))
              .then((csnap) => {
                if (csnap.exists()) setCustomerNameFetched(csnap.data().fullName || csnap.data().name || "");
              })
              .catch(() => {});
          }
        } else {
          setError("Vehicle not found.");
        }
      })
      .catch((err) => {
        console.error("Failed to fetch vehicle doc:", err);
        setError("Failed to load vehicle data.");
      })
      .finally(() => mounted && setLoadingDoc(false));
    return () => {
      mounted = false;
    };
  }, [vehicleDocId]); // eslint-disable-line

  /* ---------- auto-generate customerId from typed name ---------- */
  useEffect(() => {
    if (!customerNameInput || initialCustomerId) return;
    if (!customerId || autoGeneratedCustomerId) {
      const gen = makeCustomerIdFromName(customerNameInput);
      setCustomerId(gen);
      setAutoGeneratedCustomerId(true);
    }
  }, [customerNameInput]); // eslint-disable-line

  const onCustomerIdChange = (val) => {
    setCustomerId(val);
    setAutoGeneratedCustomerId(false);
  };

  /* ---------- fetch customer name for display ---------- */
  useEffect(() => {
    if (!customerId) {
      setCustomerNameFetched("");
      return;
    }
    if (autoGeneratedCustomerId) {
      setCustomerNameFetched(customerNameInput || "");
      return;
    }
    let mounted = true;
    setLoadingCustomer(true);
    getDoc(firestoreDoc(db, "customer", customerId))
      .then((snap) => {
        if (!mounted) return;
        if (snap.exists()) {
          const d = snap.data();
          setCustomerNameFetched(d.fullName || d.name || "");
        } else {
          setCustomerNameFetched("");
        }
      })
      .catch(() => setCustomerNameFetched(""))
      .finally(() => mounted && setLoadingCustomer(false));
    return () => {
      mounted = false;
    };
  }, [customerId, autoGeneratedCustomerId]); // eslint-disable-line

  /* ---------- auto publicId from model ---------- */
  useEffect(() => {
    if (!form.model) {
      setForm((s) => ({ ...s, publicId: "" }));
      return;
    }
    setForm((s) => ({ ...s, publicId: makePublicId(s.model) }));
  }, [form.model]); // eslint-disable-line

  /* ---------- preview logic ---------- */
  useEffect(() => {
    if (file) {
      const url = URL.createObjectURL(file);
      setPreview(url);
      return () => URL.revokeObjectURL(url);
    }
    if (existingImageUrl) {
      setPreview(existingImageUrl);
      return;
    }
    if (form.brandImageUrl && form.brandImageUrl.trim()) {
      setPreview(form.brandImageUrl.trim());
      return;
    }
    setPreview(null);
  }, [file, existingImageUrl, form.brandImageUrl]);

  const handleFileChange = (e) => {
    const f = e.target.files?.[0] || null;
    if (f && f.size > 8 * 1024 * 1024) {
      setError("Image must be smaller than 8MB.");
      e.target.value = "";
      return;
    }
    setError(null);
    setFile(f);
  };

  const clearFile = () => {
    setFile(null);
    if (fileInputRef.current) fileInputRef.current.value = "";
  };

  const validate = () => {
    if (!customerId?.trim()) {
      setError("Please provide a customer ID (or type a customer name to auto-generate one).");
      return false;
    }
    if (!form.model?.trim()) {
      setError("Model is required.");
      return false;
    }
    if (!form.brand?.trim()) {
      setError("Brand is required.");
      return false;
    }
    if (!form.licensePlateNumber.trim() && !form.registration.trim()) {
      setError("Provide license plate or registration number.");
      return false;
    }
    if (form.baseFare && isNaN(Number(form.baseFare))) {
      setError("Enter a valid number for Base Fare.");
      return false;
    }
    if (form.pricePerKm && isNaN(Number(form.pricePerKm))) {
      setError("Enter a valid number for Price per Km.");
      return false;
    }
    setError(null);
    return true;
  };

  const uploadImageToStorage = (docId) => {
    if (!file) return Promise.resolve(null);
    const safeName = file.name.replace(/\s+/g, "_");
    const path = `customer_cars/${docId}_${Date.now()}_${safeName}`;
    const sRef = storageRef(storage, path);
    const task = uploadBytesResumable(sRef, file);

    return new Promise((resolve, reject) => {
      task.on(
        "state_changed",
        (snap) => {
          const pct = snap.totalBytes ? Math.round((snap.bytesTransferred / snap.totalBytes) * 100) : 0;
          setUploadProgress(pct);
        },
        (err) => {
          console.error("Image upload failed:", err);
          setError("Image upload failed. See console.");
          reject(err);
        },
        async () => {
          try {
            const url = await getDownloadURL(task.snapshot.ref);
            resolve(url);
          } catch (gErr) {
            console.error("getDownloadURL failed:", gErr);
            setError("Failed to get upload URL.");
            reject(gErr);
          }
        }
      );
    });
  };

  /* ---------- when category changes, prefill price if not touched ---------- */
  useEffect(() => {
    const cat = form.category;
    if (!cat) return;
    const mapping = TYPE_PRICING[cat];
    if (!mapping) return;
    if (!priceTouched) {
      setForm((s) => ({
        ...s,
        baseFare: String(mapping.baseFare),
        pricePerKm: String(mapping.pricePerKm),
      }));
    }
    setCategoryAutoSelected(true);
  }, [form.category]); // eslint-disable-line

  /* ---------- when carType changes, try to detect category ---------- */
  useEffect(() => {
    const t = (form.carType || "").trim();
    if (!t) return;
    if (form.category && !categoryAutoSelected) return;

    for (const rule of CAR_TYPE_TO_CATEGORY) {
      if (rule.match.test(t)) {
        if (form.category !== rule.category) {
          setForm((s) => ({ ...s, category: rule.category }));
          if (!priceTouched) setCategoryAutoSelected(true);
        }
        return;
      }
    }
  }, [form.carType]); // eslint-disable-line

  /* ---------- submit (create / edit) ---------- */
  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!validate()) return;

    setSubmitting(true);
    setUploadProgress(0);
    setError(null);

    try {
      const parsedBaseFare = form.baseFare !== "" ? Number(form.baseFare) : null;
      const parsedPricePerKm = form.pricePerKm !== "" ? Number(form.pricePerKm) : null;

      const basePayload = {
        brand: form.brand.trim() || null,
        brandImage: form.brandImageUrl?.trim() || null,
        model: form.model?.trim() || null,
        publicId: form.publicId || makePublicId(form.model),
        carType: form.carType?.trim() || null,
        category: form.category?.trim() || null,
        licensePlateNumber: form.licensePlateNumber?.trim() || null,
        registration: form.registration?.trim() || null,
        color: form.color?.trim() || null,
        seats: form.seats?.trim() || null,
        transmission: form.transmission?.trim() || null,
        fuelType: form.fuelType?.trim() || null,
        city: form.city?.trim() || null,
        yearOfManufacture: form.yearOfManufacture?.trim() || null,
        baseFare: parsedBaseFare,
        pricePerKm: parsedPricePerKm,
        customerId: customerId.trim(),
        uid: customerId.trim(),
        updatedAt: serverTimestamp(),
      };

      if (isEdit && vehicleDocId) {
        const docRef = firestoreDoc(db, "customer_cars", vehicleDocId);
        await updateDoc(docRef, { ...basePayload });

        if (file) {
          try {
            const url = await uploadImageToStorage(vehicleDocId);
            if (url) {
              await updateDoc(docRef, { image: url, id: vehicleDocId, uid: customerId.trim(), updatedAt: serverTimestamp() });
              setExistingImageUrl(url);
            }
          } catch (err) {
            console.warn("Image upload failed during edit:", err);
            setError("Updated vehicle but image upload failed. See console.");
          }
        } else if (form.brandImageUrl && form.brandImageUrl.trim()) {
          try {
            await updateDoc(docRef, { image: form.brandImageUrl.trim(), id: vehicleDocId, uid: customerId.trim(), updatedAt: serverTimestamp() });
            setExistingImageUrl(form.brandImageUrl.trim());
          } catch (err) {
            console.warn("Patch image from brandImageUrl failed:", err);
          }
        } else {
          await updateDoc(docRef, { id: vehicleDocId, uid: customerId.trim(), updatedAt: serverTimestamp() });
        }
      } else {
        const payload = { ...basePayload, createdAt: serverTimestamp(), id: null, image: null };
        const colRef = collection(db, "customer_cars");
        const docRef = await addDoc(colRef, payload);
        const docId = docRef.id;
        const friendlyId = generateFriendlyId(form.model);

        if (file) {
          try {
            const url = await uploadImageToStorage(docId);
            const patch = { id: friendlyId, uid: customerId.trim(), updatedAt: serverTimestamp() };
            if (url) patch.image = url;
            await updateDoc(firestoreDoc(db, "customer_cars", docId), patch);
          } catch (err) {
            console.warn("Image upload failed during create:", err);
            try {
              await updateDoc(firestoreDoc(db, "customer_cars", docId), { id: friendlyId, uid: customerId.trim(), updatedAt: serverTimestamp() });
            } catch {}
            setError("Vehicle created but image upload failed. See console.");
          }
        } else if (form.brandImageUrl && form.brandImageUrl.trim()) {
          try {
            await updateDoc(firestoreDoc(db, "customer_cars", docId), {
              image: form.brandImageUrl.trim(),
              id: friendlyId,
              uid: customerId.trim(),
              updatedAt: serverTimestamp(),
            });
          } catch (err) {
            console.warn("Patch created doc with brandImageUrl failed:", err);
          }
        } else {
          await updateDoc(firestoreDoc(db, "customer_cars", docId), { id: friendlyId, uid: customerId.trim(), updatedAt: serverTimestamp() });
        }
      }

      // After successful save, navigate back to customers (VehicleList will reflect changes realtime)
      navigate("/customers");
    } catch (err) {
      console.error("Add/update vehicle failed:", err);
      setError("Failed to save vehicle. Check console and Firestore rules.");
    } finally {
      setSubmitting(false);
      setUploadProgress(0);
      setFile(null);
      setPreview(null);
    }
  };

  const handleDelete = async () => {
    if (!isEdit || !vehicleDocId) return;
    if (!confirm("Delete this vehicle permanently?")) return;
    setSubmitting(true);
    setError(null);
    try {
      await deleteDoc(firestoreDoc(db, "customer_cars", vehicleDocId));
      navigate("/customers");
    } catch (err) {
      console.error("Delete vehicle failed:", err);
      setError("Failed to delete vehicle. See console.");
      setSubmitting(false);
    }
  };

  function categoryPricingHint(cat) {
    if (!cat) return null;
    const p = TYPE_PRICING[cat] || TYPE_PRICING.Default;
    return `Base Fare: AED ${p.baseFare.toFixed(2)} | Price per Km: AED ${p.pricePerKm.toFixed(2)}`;
  }

  return (
    <div className="min-h-screen bg-slate-50 py-4 px-3">
      <div className="mx-auto w-full max-w-[360px] sm:max-w-2xl">
        <motion.div initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.28 }} className="mb-3">
          <div className="flex items-center justify-between gap-3">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-indigo-600 flex items-center justify-center text-white shadow-sm">
                <Icons.Truck className="transform scale-90" />
              </div>
              <div>
                <h2 className="text-lg font-semibold">{isEdit ? "Edit Vehicle" : "Add Vehicle"}</h2>
                <p className="text-xs text-slate-500">{isEdit ? "Edit fields and optionally upload a new image." : "Type a customer name to auto-generate an ID. Model & Brand required."}</p>
              </div>
            </div>

            <div className="text-right text-xs text-slate-400">
              <div>{customerNameFetched ? <span className="font-medium text-slate-700">{customerNameFetched}</span> : <span className="italic">No customer name</span>}</div>
              <div className="mt-1">{loadingCustomer ? "Checking…" : (customerId ? customerId : "No ID")}</div>
            </div>
          </div>
        </motion.div>

        {loadingDoc && isEdit ? (
          <div className="p-4 bg-white rounded shadow text-center">Loading vehicle…</div>
        ) : (
          <motion.form onSubmit={handleSubmit} initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="bg-white rounded-xl shadow-sm p-3 sm:p-5 space-y-3">
            {error && (
              <div className="text-xs text-rose-600 flex items-center gap-2">
                <Icons.AlertTriangle size={14} /> <span>{error}</span>
              </div>
            )}

            {/* customer id & name row */}
            <div>
              <label className="block text-xs text-slate-600">Customer ID (required)</label>
              <div className="mt-2 flex flex-col sm:flex-row gap-2">
                <input
                  value={customerId}
                  onChange={(e) => onCustomerIdChange(e.target.value)}
                  className="flex-1 border rounded px-2 py-2 text-sm"
                  placeholder="customer document id (editable)"
                />
                <input
                  value={customerNameInput || customerNameFetched}
                  onChange={(e) => setCustomerNameInput(e.target.value)}
                  className="w-full sm:w-64 border rounded px-2 py-2 text-sm"
                  placeholder="Customer name (type to auto-gen id)"
                />
              </div>
              <div className="text-[11px] text-slate-400 mt-1">If opened from a customer row, ID is prefilled. Typing a name auto-generates an ID (editable).</div>
            </div>

            {/* two-column compact grid */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              <div>
                <label className="block text-xs text-slate-600">Brand *</label>
                <input value={form.brand} onChange={(e) => setForm((s) => ({ ...s, brand: e.target.value }))} className="mt-1 border rounded px-2 py-2 text-sm" placeholder="BMW, Toyota..." required />
              </div>

              <div>
                <label className="block text-xs text-slate-600">Brand image URL</label>
                <input value={form.brandImageUrl} onChange={(e) => setForm((s) => ({ ...s, brandImageUrl: e.target.value }))} className="mt-1 border rounded px-2 py-2 text-sm" placeholder="https://..." />
                <div className="text-[11px] text-slate-400 mt-1">Optional thumbnail; you can also upload an image below.</div>
              </div>

              <div>
                <label className="block text-xs text-slate-600">Model *</label>
                <input value={form.model} onChange={(e) => setForm((s) => ({ ...s, model: e.target.value }))} className="mt-1 border rounded px-2 py-2 text-sm" placeholder="Swift, Corolla..." required />
              </div>

              <div>
                <label className="block text-xs text-slate-600">Public ID (auto)</label>
                <input value={form.publicId} readOnly className="mt-1 border rounded px-2 py-2 text-sm bg-slate-50" />
                <div className="text-[11px] text-slate-400 mt-1">Generated from model.</div>
              </div>

              <div>
                <label className="block text-xs text-slate-600">Car type</label>
                <input
                  value={form.carType}
                  onChange={(e) => {
                    setForm((s) => ({ ...s, carType: e.target.value }));
                    setCategoryAutoSelected(false);
                  }}
                  className="mt-1 border rounded px-2 py-2 text-sm"
                  placeholder="Hatchback, Sedan, SUV..."
                />
              </div>

              <div>
                <label className="block text-xs text-slate-600">Vehicle Category</label>
                <select
                  value={form.category}
                  onChange={(e) => {
                    const val = e.target.value;
                    setForm((s) => ({ ...s, category: val }));
                    setCategoryAutoSelected(false);
                  }}
                  className="mt-1 border rounded px-2 py-2 text-sm bg-white"
                >
                  <option value="">-- Select category (optional) --</option>
                  {CATEGORY_OPTIONS.map((opt) => (
                    <option key={opt} value={opt}>
                      {opt}
                    </option>
                  ))}
                </select>

                {/* pricing hint */}
                {form.category ? (
                  <div className="text-[12px] mt-1 text-slate-500">
                    {categoryPricingHint(form.category)}
                  </div>
                ) : (
                  <div className="text-[11px] text-slate-400 mt-1">Category maps to default pricing. Leave empty to use default mapping.</div>
                )}
              </div>

              <div>
                <label className="block text-xs text-slate-600">License plate</label>
                <input value={form.licensePlateNumber} onChange={(e) => setForm((s) => ({ ...s, licensePlateNumber: e.target.value }))} className="mt-1 border rounded px-2 py-2 text-sm" placeholder="1234" />
              </div>

              <div>
                <label className="block text-xs text-slate-600">Registration</label>
                <input value={form.registration} onChange={(e) => setForm((s) => ({ ...s, registration: e.target.value }))} className="mt-1 border rounded px-2 py-2 text-sm" placeholder="Reg id" />
              </div>

              <div>
                <label className="block text-xs text-slate-600">Seats</label>
                <input value={form.seats} onChange={(e) => setForm((s) => ({ ...s, seats: e.target.value }))} className="mt-1 border rounded px-2 py-2 text-sm" placeholder="4" />
              </div>

              <div>
                <label className="block text-xs text-slate-600">Transmission</label>
                <input value={form.transmission} onChange={(e) => setForm((s) => ({ ...s, transmission: e.target.value }))} className="mt-1 border rounded px-2 py-2 text-sm" placeholder="Manual, Automatic" />
              </div>

              <div>
                <label className="block text-xs text-slate-600">Fuel type</label>
                <input value={form.fuelType} onChange={(e) => setForm((s) => ({ ...s, fuelType: e.target.value }))} className="mt-1 border rounded px-2 py-2 text-sm" placeholder="Petrol, Diesel, EV..." />
              </div>

              <div>
                <label className="block text-xs text-slate-600">Year</label>
                <input value={form.yearOfManufacture} onChange={(e) => setForm((s) => ({ ...s, yearOfManufacture: e.target.value }))} className="mt-1 border rounded px-2 py-2 text-sm" placeholder="2025" />
              </div>

              <div>
                <label className="block text-xs text-slate-600">Color</label>
                <input value={form.color} onChange={(e) => setForm((s) => ({ ...s, color: e.target.value }))} className="mt-1 border rounded px-2 py-2 text-sm" placeholder="Black" />
              </div>

              <div>
                <label className="block text-xs text-slate-600">City</label>
                <input value={form.city} onChange={(e) => setForm((s) => ({ ...s, city: e.target.value }))} className="mt-1 border rounded px-2 py-2 text-sm" placeholder="City name" />
              </div>

              {/* New pricing inputs */}
              <div>
                <label className="block text-xs text-slate-600">Base Fare (AED)</label>
                <input
                  value={form.baseFare}
                  onChange={(e) => {
                    setForm((s) => ({ ...s, baseFare: e.target.value }));
                    setPriceTouched(true);
                  }}
                  className="mt-1 border rounded px-2 py-2 text-sm"
                  placeholder="e.g., 8.0"
                  type="number"
                  step="0.1"
                  min="0"
                />
                <div className="text-[11px] text-slate-400 mt-1">Optional: will be saved to vehicle doc and used for fare calculations.</div>
              </div>

              <div>
                <label className="block text-xs text-slate-600">Price per Km (AED)</label>
                <input
                  value={form.pricePerKm}
                  onChange={(e) => {
                    setForm((s) => ({ ...s, pricePerKm: e.target.value }));
                    setPriceTouched(true);
                  }}
                  className="mt-1 border rounded px-2 py-2 text-sm"
                  placeholder="e.g., 2.0"
                  type="number"
                  step="0.1"
                  min="0"
                />
                <div className="text-[11px] text-slate-400 mt-1">Optional: will be saved to vehicle doc and used for fare calculations.</div>
              </div>
            </div>

            {/* image row compact */}
            <div className="flex flex-col sm:flex-row sm:items-center gap-3">
              <div className="flex items-center gap-3">
                <input ref={fileInputRef} id="vehicleImageFile" type="file" accept="image/*" onChange={handleFileChange} className="hidden" />
                <label htmlFor="vehicleImageFile" className="cursor-pointer px-2 py-1 rounded border text-sm inline-flex items-center gap-2 bg-white">
                  <Icons.Image size={14} /> Upload
                </label>

                {file ? (
                  <button type="button" onClick={clearFile} className="px-2 py-1 rounded border text-sm bg-slate-100">Clear</button>
                ) : null}
              </div>

              <div className="flex items-center gap-3">
                {preview ? (
                  <div className="w-28 h-20 border rounded overflow-hidden">
                    <img src={preview} alt="preview" className="w-full h-full object-cover" onError={(e) => (e.currentTarget.style.display = "none")} />
                  </div>
                ) : (
                  <div className="w-28 h-20 border rounded bg-slate-50 flex items-center justify-center text-xs text-slate-400">No image</div>
                )}

                <div className="text-xs text-slate-400">
                  Max size 8MB. Preview shown here.
                </div>
              </div>
            </div>

            {uploadProgress > 0 && (
              <div>
                <div className="h-2 bg-slate-100 rounded overflow-hidden">
                  <motion.div animate={{ width: `${uploadProgress}%` }} className="h-full bg-indigo-500" />
                </div>
                <div className="text-[11px] text-slate-500 mt-1">Uploading: {uploadProgress}%</div>
              </div>
            )}

            {/* actions */}
            <div className="flex flex-col sm:flex-row gap-2 justify-end items-center">
              {isEdit && (
                <button type="button" onClick={handleDelete} disabled={submitting} className="w-full sm:w-auto px-3 py-2 rounded bg-rose-600 text-white text-sm">
                  {submitting ? "Processing..." : "Delete Vehicle"}
                </button>
              )}

              <div className="flex gap-2 w-full sm:w-auto">
                <Link to="/customers" className="flex-1 sm:flex-none">
                  <button type="button" disabled={submitting} className="w-full px-3 py-2 rounded bg-slate-100 text-sm">Cancel</button>
                </Link>

                <button type="submit" disabled={submitting} className="w-full sm:w-auto px-3 py-2 rounded bg-emerald-600 text-white text-sm flex items-center gap-2 justify-center">
                  {submitting ? <><Icons.Loader2 className="animate-spin" size={14} /> <span>Saving...</span></> : <><Icons.PlusCircle size={14} /> <span>{isEdit ? "Save Changes" : "Add Vehicle"}</span></>}
                </button>
              </div>
            </div>
          </motion.form>
        )}
      </div>
    </div>
  );
}
