// src/pages/AddVehicle.jsx
import React, { useEffect, useRef, useState } from "react";
import { useNavigate, useLocation, Link } from "react-router-dom";
import * as Icons from "lucide-react";
import { motion } from "framer-motion";
import {
    addDoc,
    collection,
    doc as firestoreDoc,
    getDoc,
    updateDoc,
    deleteDoc,
    serverTimestamp,
} from "firebase/firestore";
import { ref as storageRef, uploadBytesResumable, getDownloadURL } from "firebase/storage";
import { db, storage } from "../../firebase"; // <-- ensure these are exported correctly

function useQuery() {
    const { search } = useLocation();
    return React.useMemo(() => new URLSearchParams(search), [search]);
}

function makePublicId(model = "") {
    const base = model ? model.trim().replace(/\s+/g, "_").replace(/[^\w\-]/g, "") : "veh";
    const suffix = String(Date.now()).slice(-5);
    return `${base}_${suffix}`;
}

function makeCustomerIdFromName(name = "") {
    const base = name
        .toLowerCase()
        .trim()
        .split(" ")
        .slice(0, 2)
        .map((p) => p.replace(/[^\w]/g, ""))
        .join("_")
        .slice(0, 12) || "cust";
    const suffix = String(Date.now()).slice(-6);
    return `${base}_${suffix}`;
}
export default function AddVehicle() {
    const navigate = useNavigate();
    const q = useQuery();
    const initialCustomerId = q.get("customerId") || "";
    const vehicleIdParam = q.get("vehicleId") || null;

    const fileInputRef = useRef(null);

    const [isEdit, setIsEdit] = useState(Boolean(vehicleIdParam));
    const [vehicleDocId, setVehicleDocId] = useState(vehicleIdParam || null);

    const [customerNameInput, setCustomerNameInput] = useState("");
    const [customerNameFetched, setCustomerNameFetched] = useState("");
    const [loadingCustomer, setLoadingCustomer] = useState(false);

    const [customerId, setCustomerId] = useState(initialCustomerId);
    const [autoGeneratedCustomerId, setAutoGeneratedCustomerId] = useState(false);

    const [form, setForm] = useState({
        brand: "",
        brandImageUrl: "",
        model: "",
        publicId: "",
        carType: "",
        licensePlateNumber: "",
        registration: "",
        color: "",
        seats: "",
        transmission: "",
        fuelType: "",
        city: "",
        yearOfManufacture: "",
    });

    const [existingImageUrl, setExistingImageUrl] = useState(null);
    const [file, setFile] = useState(null);
    const [preview, setPreview] = useState(null);
    const [uploadProgress, setUploadProgress] = useState(0);

    const [loadingDoc, setLoadingDoc] = useState(false);
    const [submitting, setSubmitting] = useState(false);
    const [error, setError] = useState(null);

    // load doc when editing
    useEffect(() => {
        if (!vehicleDocId) return;
        let mounted = true;
        setLoadingDoc(true);
        getDoc(firestoreDoc(db, "customer_cars", vehicleDocId))
            .then((snap) => {
                if (!mounted) return;
                if (snap.exists()) {
                    const d = snap.data();
                    setForm({
                        brand: d.brand || "",
                        brandImageUrl: d.brandImage || "",
                        model: d.model || "",
                        publicId: d.publicId || (d.model ? makePublicId(d.model) : ""),
                        carType: d.carType || "",
                        licensePlateNumber: d.licensePlateNumber || "",
                        registration: d.registration || "",
                        color: d.color || "",
                        seats: d.seats || "",
                        transmission: d.transmission || "",
                        fuelType: d.fuelType || "",
                        city: d.city || "",
                        yearOfManufacture: d.yearOfManufacture || "",
                    });
                    setExistingImageUrl(d.image || d.brandImage || null);
                    if (!customerId && d.customerId) {
                        setCustomerId(d.customerId);
                        setAutoGeneratedCustomerId(false);
                    }
                    if (d.customerId) {
                        getDoc(firestoreDoc(db, "customer", d.customerId))
                            .then((csnap) => {
                                if (csnap.exists()) setCustomerNameFetched(csnap.data().fullName || csnap.data().name || "");
                            })
                            .catch(() => { });
                    }
                } else {
                    setError("Vehicle not found.");
                }
            })
            .catch((err) => {
                console.error("Failed to fetch vehicle doc:", err);
                setError("Failed to load vehicle data.");
            })
            .finally(() => mounted && setLoadingDoc(false));
        return () => {
            mounted = false;
        };
    }, [vehicleDocId]);

    // auto-generate customerId from typed name (unless already provided)
    useEffect(() => {
        if (!customerNameInput || initialCustomerId) return;
        if (!customerId || autoGeneratedCustomerId) {
            const gen = makeCustomerIdFromName(customerNameInput);
            setCustomerId(gen);
            setAutoGeneratedCustomerId(true);
        }
    }, [customerNameInput]); // eslint-disable-line

    const onCustomerIdChange = (val) => {
        setCustomerId(val);
        setAutoGeneratedCustomerId(false);
    };

    // fetch customer name for display, skip fetch if ID auto-generated
    useEffect(() => {
        if (!customerId) {
            setCustomerNameFetched("");
            return;
        }
        if (autoGeneratedCustomerId) {
            setCustomerNameFetched(customerNameInput || "");
            return;
        }
        let mounted = true;
        setLoadingCustomer(true);
        getDoc(firestoreDoc(db, "customer", customerId))
            .then((snap) => {
                if (!mounted) return;
                if (snap.exists()) {
                    const d = snap.data();
                    setCustomerNameFetched(d.fullName || d.name || "");
                } else {
                    setCustomerNameFetched("");
                }
            })
            .catch(() => setCustomerNameFetched(""))
            .finally(() => mounted && setLoadingCustomer(false));
        return () => {
            mounted = false;
        };
    }, [customerId, autoGeneratedCustomerId]); // eslint-disable-line

    // auto publicId from model
    useEffect(() => {
        if (!form.model) {
            setForm((s) => ({ ...s, publicId: "" }));
            return;
        }
        setForm((s) => ({ ...s, publicId: makePublicId(s.model) }));
    }, [form.model]); // eslint-disable-line

    // preview logic
    useEffect(() => {
        if (file) {
            const url = URL.createObjectURL(file);
            setPreview(url);
            return () => URL.revokeObjectURL(url);
        }
        if (existingImageUrl) {
            setPreview(existingImageUrl);
            return;
        }
        if (form.brandImageUrl && form.brandImageUrl.trim()) {
            setPreview(form.brandImageUrl.trim());
            return;
        }
        setPreview(null);
    }, [file, existingImageUrl, form.brandImageUrl]);

    const handleFileChange = (e) => {
        const f = e.target.files?.[0] || null;
        if (f && f.size > 8 * 1024 * 1024) {
            setError("Image must be smaller than 8MB.");
            e.target.value = "";
            return;
        }
        setError(null);
        setFile(f);
    };

    const clearFile = () => {
        setFile(null);
        if (fileInputRef.current) fileInputRef.current.value = "";
    };

    const validate = () => {
        if (!customerId?.trim()) {
            setError("Please provide a customer ID (or type a customer name to auto-generate one).");
            return false;
        }
        if (!form.model?.trim()) {
            setError("Model is required.");
            return false;
        }
        if (!form.brand?.trim()) {
            setError("Brand is required.");
            return false;
        }
        if (!form.licensePlateNumber.trim() && !form.registration.trim()) {
            setError("Provide license plate or registration number.");
            return false;
        }
        setError(null);
        return true;
    };

    // Upload helper: returns download URL or null
    const uploadImageToStorage = (docId) => {
        if (!file) return Promise.resolve(null);
        const safeName = file.name.replace(/\s+/g, "_");
        const path = `customer_cars/${docId}_${Date.now()}_${safeName}`;
        const sRef = storageRef(storage, path);
        const task = uploadBytesResumable(sRef, file);

        return new Promise((resolve, reject) => {
            task.on(
                "state_changed",
                (snap) => {
                    const pct = snap.totalBytes ? Math.round((snap.bytesTransferred / snap.totalBytes) * 100) : 0;
                    setUploadProgress(pct);
                },
                (err) => {
                    console.error("Image upload failed:", err);
                    setError("Image upload failed. See console.");
                    reject(err);
                },
                async () => {
                    try {
                        const url = await getDownloadURL(task.snapshot.ref);
                        resolve(url);
                    } catch (gErr) {
                        console.error("getDownloadURL failed:", gErr);
                        setError("Failed to get upload URL.");
                        reject(gErr);
                    }
                }
            );
        });
    };

    // generate a friendly short id (fast). If you need strictly sequential numeric IDs, use server-side logic.
    const generateFriendlyId = (model = "") => {
        const base = model ? model.trim().replace(/\s+/g, "_").replace(/[^\w\-]/g, "") : "veh";
        const t = String(Date.now()).slice(-6);
        return `${base}_${t}`;
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        if (!validate()) return;

        setSubmitting(true);
        setUploadProgress(0);
        setError(null);

        try {
            const basePayload = {
                brand: form.brand.trim() || null,
                brandImage: form.brandImageUrl?.trim() || null,
                carType: form.carType?.trim() || null,
                city: form.city?.trim() || null,
                color: form.color?.trim() || null,
                customerId: customerId.trim(),
                uid: customerId.trim(),
                fuelType: form.fuelType?.trim() || null,
                licensePlateNumber: form.licensePlateNumber?.trim() || null,
                registration: form.registration?.trim() || null,
                model: form.model?.trim() || null,
                seats: form.seats?.trim() || null,
                transmission: form.transmission?.trim() || null,
                yearOfManufacture: form.yearOfManufacture?.trim() || null,
                publicId: form.publicId || makePublicId(form.model),
                updatedAt: serverTimestamp(),
            };

            if (isEdit && vehicleDocId) {
                // EDIT flow
                const docRef = firestoreDoc(db, "customer_cars", vehicleDocId);
                await updateDoc(docRef, { ...basePayload });

                // if file uploaded -> upload and patch image
                if (file) {
                    try {
                        const url = await uploadImageToStorage(vehicleDocId);
                        if (url) {
                            await updateDoc(docRef, { image: url, id: vehicleDocId, uid: customerId.trim(), updatedAt: serverTimestamp() });
                            setExistingImageUrl(url);
                        }
                    } catch (err) {
                        console.warn("Image upload failed during edit:", err);
                        setError("Updated vehicle but image upload failed. See console.");
                    }
                } else if (form.brandImageUrl && form.brandImageUrl.trim()) {
                    try {
                        await updateDoc(docRef, { image: form.brandImageUrl.trim(), id: vehicleDocId, uid: customerId.trim(), updatedAt: serverTimestamp() });
                        setExistingImageUrl(form.brandImageUrl.trim());
                    } catch (err) {
                        console.warn("Patch image from brandImageUrl failed:", err);
                    }
                } else {
                    await updateDoc(docRef, { id: vehicleDocId, uid: customerId.trim(), updatedAt: serverTimestamp() });
                }
            } else {
                // CREATE flow (simplified & reliable)
                const payload = { ...basePayload, createdAt: serverTimestamp(), id: null, image: null };
                const colRef = collection(db, "customer_cars");
                const docRef = await addDoc(colRef, payload);
                const docId = docRef.id;
                const friendlyId = generateFriendlyId(form.model);

                // If file exists -> upload, then update in one patch
                if (file) {
                    try {
                        const url = await uploadImageToStorage(docId);
                        const patch = {
                            id: friendlyId,
                            uid: customerId.trim(),
                            updatedAt: serverTimestamp(),
                        };
                        if (url) patch.image = url;
                        await updateDoc(firestoreDoc(db, "customer_cars", docId), patch);
                    } catch (err) {
                        console.warn("Image upload failed during create:", err);
                        // still patch id so doc isn't left without id
                        try {
                            await updateDoc(firestoreDoc(db, "customer_cars", docId), { id: friendlyId, uid: customerId.trim(), updatedAt: serverTimestamp() });
                        } catch (ignore) { }
                        setError("Vehicle created but image upload failed. See console.");
                    }
                } else if (form.brandImageUrl && form.brandImageUrl.trim()) {
                    try {
                        await updateDoc(firestoreDoc(db, "customer_cars", docId), {
                            image: form.brandImageUrl.trim(),
                            id: friendlyId,
                            uid: customerId.trim(),
                            updatedAt: serverTimestamp(),
                        });
                    } catch (err) {
                        console.warn("Patch created doc with brandImageUrl failed:", err);
                    }
                } else {
                    // no image
                    await updateDoc(firestoreDoc(db, "customer_cars", docId), {
                        id: friendlyId,
                        uid: customerId.trim(),
                        updatedAt: serverTimestamp(),
                    });
                }
            }
            navigate("/customers");
        } catch (err) {
            console.error("Add/update vehicle failed:", err);
            setError("Failed to save vehicle. Check console and Firestore rules.");
        } finally {
            setSubmitting(false);
            setUploadProgress(0);
            setFile(null);
            setPreview(null);
        }
    };

    const handleDelete = async () => {
        if (!isEdit || !vehicleDocId) return;
        if (!confirm("Delete this vehicle permanently?")) return;
        setSubmitting(true);
        setError(null);
        try {
            await deleteDoc(firestoreDoc(db, "customer_cars", vehicleDocId));
            navigate("/customers");
        } catch (err) {
            console.error("Delete vehicle failed:", err);
            setError("Failed to delete vehicle. See console.");
            setSubmitting(false);
        }
    };

    return (
        <div className="p-6 max-w-3xl mx-auto">
            <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.35 }} className="mb-4">
                <h2 className="text-xl font-semibold">{isEdit ? "Edit Vehicle" : "Add Vehicle"}</h2>
                <p className="text-sm text-slate-500">
                    {isEdit ? "Edit fields and optionally upload a new image." : "Type a customer name to auto-generate a customer ID. Model & Brand required."}
                </p>
            </motion.div>

            {(loadingDoc && isEdit) ? (
                <div className="p-6 bg-white rounded shadow text-center">Loading vehicle…</div>
            ) : (
                <form onSubmit={handleSubmit} className="bg-white rounded-lg shadow p-6 space-y-4">
                    {error && (
                        <div className="text-sm text-rose-600">
                            <Icons.AlertTriangle className="inline mr-2" size={14} /> {error}
                        </div>
                    )}

                    <div>
                        <label className="block text-xs text-slate-600">Customer ID (required)</label>
                        <div className="mt-1 flex gap-2">
                            <input
                                value={customerId}
                                onChange={(e) => onCustomerIdChange(e.target.value)}
                                className="flex-1 border rounded px-3 py-2"
                                placeholder="customer document id (editable)"
                            />
                            <input
                                value={customerNameInput || customerNameFetched}
                                onChange={(e) => setCustomerNameInput(e.target.value)}
                                className="w-56 border rounded px-3 py-2 bg-white"
                                placeholder="Customer name (type to auto-generate id)"
                            />
                        </div>
                        <div className="text-xs text-slate-400 mt-1">
                            If you opened this from the customer's row, ID is filled. Typing a name will auto-generate an ID (you can edit the ID manually).
                        </div>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                        <div>
                            <label className="block text-xs text-slate-600">Brand *</label>
                            <input
                                value={form.brand}
                                onChange={(e) => setForm((s) => ({ ...s, brand: e.target.value }))}
                                className="mt-1 border rounded px-3 py-2 w-full"
                                placeholder="BMW, Toyota..."
                                required
                            />
                        </div>

                        <div>
                            <label className="block text-xs text-slate-600">Brand image URL (optional)</label>
                            <input
                                value={form.brandImageUrl}
                                onChange={(e) => setForm((s) => ({ ...s, brandImageUrl: e.target.value }))}
                                className="mt-1 border rounded px-3 py-2 w-full"
                                placeholder="https://... (external thumbnail)"
                            />
                            <div className="text-xs text-slate-400 mt-1">Paste external thumbnail or upload a file below.</div>
                        </div>

                        <div>
                            <label className="block text-xs text-slate-600">Model *</label>
                            <input
                                value={form.model}
                                onChange={(e) => setForm((s) => ({ ...s, model: e.target.value }))}
                                className="mt-1 border rounded px-3 py-2 w-full"
                                placeholder="Swift, Corolla..."
                                required
                            />
                        </div>

                        <div>
                            <label className="block text-xs text-slate-600">Public ID (auto)</label>
                            <input value={form.publicId} readOnly className="mt-1 border rounded px-3 py-2 w-full bg-slate-50" />
                            <div className="text-xs text-slate-400 mt-1">Automatically generated from model.</div>
                        </div>

                        <div>
                            <label className="block text-xs text-slate-600">Car type</label>
                            <input value={form.carType} onChange={(e) => setForm((s) => ({ ...s, carType: e.target.value }))} className="mt-1 border rounded px-3 py-2 w-full" placeholder="Hatchback, Sedan..." />
                        </div>

                        <div>
                            <label className="block text-xs text-slate-600">License plate number</label>
                            <input value={form.licensePlateNumber} onChange={(e) => setForm((s) => ({ ...s, licensePlateNumber: e.target.value }))} className="mt-1 border rounded px-3 py-2 w-full" placeholder="1234" />
                        </div>

                        <div>
                            <label className="block text-xs text-slate-600">Registration number</label>
                            <input value={form.registration} onChange={(e) => setForm((s) => ({ ...s, registration: e.target.value }))} className="mt-1 border rounded px-3 py-2 w-full" placeholder="Reg id" />
                        </div>

                        <div>
                            <label className="block text-xs text-slate-600">Seats</label>
                            <input value={form.seats} onChange={(e) => setForm((s) => ({ ...s, seats: e.target.value }))} className="mt-1 border rounded px-3 py-2 w-full" placeholder="4" />
                        </div>

                        <div>
                            <label className="block text-xs text-slate-600">Transmission</label>
                            <input value={form.transmission} onChange={(e) => setForm((s) => ({ ...s, transmission: e.target.value }))} className="mt-1 border rounded px-3 py-2 w-full" placeholder="Manual, Automatic" />
                        </div>

                        <div>
                            <label className="block text-xs text-slate-600">Fuel type</label>
                            <input value={form.fuelType} onChange={(e) => setForm((s) => ({ ...s, fuelType: e.target.value }))} className="mt-1 border rounded px-3 py-2 w-full" placeholder="Petrol, Diesel, EV..." />
                        </div>

                        <div>
                            <label className="block text-xs text-slate-600">Year of manufacture</label>
                            <input value={form.yearOfManufacture} onChange={(e) => setForm((s) => ({ ...s, yearOfManufacture: e.target.value }))} className="mt-1 border rounded px-3 py-2 w-full" placeholder="2025" />
                        </div>

                        <div>
                            <label className="block text-xs text-slate-600">Color</label>
                            <input value={form.color} onChange={(e) => setForm((s) => ({ ...s, color: e.target.value }))} className="mt-1 border rounded px-3 py-2 w-full" placeholder="Black" />
                        </div>

                        <div>
                            <label className="block text-xs text-slate-600">City</label>
                            <input value={form.city} onChange={(e) => setForm((s) => ({ ...s, city: e.target.value }))} className="mt-1 border rounded px-3 py-2 w-full" placeholder="City name" />
                        </div>
                    </div>

                    <div>
                        <div className="mt-2 flex items-center gap-3">
                            <input ref={fileInputRef} id="vehicleImageFile" type="file" accept="image/*" onChange={handleFileChange} className="hidden" />

                            {file ? (
                                <>
                                    <button type="button" onClick={clearFile} className="px-3 py-2 rounded border bg-slate-100">Clear</button>
                                    <div className="w-28 h-20 border rounded overflow-hidden">
                                        {preview ? <img src={preview} alt="preview" className="w-full h-full object-cover" /> : null}
                                    </div>
                                </>
                            ) : preview ? (
                                <div className="w-28 h-20 border rounded overflow-hidden">
                                    <img src={preview} alt="preview" className="w-full h-full object-cover" onError={(e) => (e.currentTarget.style.display = "none")} />
                                </div>
                            ) : (
                                <div className="w-28 h-20 border rounded bg-slate-50 flex items-center justify-center text-slate-400">No image</div>
                            )}
                        </div>

                        {uploadProgress > 0 && (
                            <div className="mt-2">
                                <div className="h-2 bg-slate-100 rounded overflow-hidden">
                                    <motion.div animate={{ width: `${uploadProgress}%` }} className="h-full bg-indigo-500" />
                                </div>
                                <div className="text-xs text-slate-500 mt-1">Uploading: {uploadProgress}%</div>
                            </div>
                        )}
                    </div>

                    <div className="flex justify-between items-center gap-3 pt-2">
                        <div>
                            {isEdit && (
                                <button type="button" onClick={handleDelete} disabled={submitting} className="px-4 py-2 rounded bg-rose-600 text-white hover:bg-rose-700">
                                    {submitting ? "Processing..." : "Delete Vehicle"}
                                </button>
                            )}
                        </div>

                        <div className="flex gap-3">
                            <Link to="/customers">
                                <button type="button" disabled={submitting} className="px-4 py-2 rounded bg-slate-50 hover:bg-slate-100">Cancel</button>
                            </Link>

                            <button type="submit" disabled={submitting} className="px-4 py-2 rounded bg-emerald-600 text-white hover:bg-emerald-700 flex items-center gap-2">
                                {submitting ? <><Icons.Loader2 className="animate-spin" size={16} /> <span>Saving...</span></> : <><Icons.PlusCircle size={16} /> <span>{isEdit ? "Save Changes" : "Add Vehicle"}</span></>}
                            </button>
                        </div>
                    </div>
                </form>
            )}
        </div>
    );
}
